name: Flutter Build for Linux and Web

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

defaults:
  run:
    # Flutter does not like the project name,
    # so use with underscore
    working-directory: ./humanbeans_clock

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./humanbeans_clock
    steps:
      - uses: actions/checkout@v3
        with:
          path: ./humanbeans_clock
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          pwd
          ls -ahl
      - run: flutter create .
      - run: flutter pub upgrade
      - run: flutter build linux
      - run: flutter build web
      - run: ls -ahl build/
